### ISSUE TITLE
Upgrade PHP 7.2 to PHP 7.4

### ISSUE THREAD

**Issue by a6smile** [gnulinuxid/alphp#1]
Bagaimana cara upgrade dari php v7.2 menjadi php v7.4?

**Comment by nggit** [comment]
@a6smile harus diedit beberapa. besok saya proses. trims.

**Comment by nggit** [comment]
@a6smile sudah saya update https://github.com/gnulinuxid/alphp/releases

**Comment by a6smile** [comment]
mysql tidak tersambung. pesan error mysqld: One can only use the --user switch if running as root

**Comment by a6smile** [comment]
setelah saya jalankan versi 7.4 pada database keluar error spt ini 

Note] mysqld: ready for connections.
Version: '10.5.12-MariaDB' socket: '/run/mysqld/mysqld.sock' port: 0 MariaDB Server
PHP Warning: mysqli::__construct(): (HY000/2002): Connection refused in

terlihat port mysql nya jadi 0 bukan 3306

bagaimana cara memperbaikinya?

**Comment by nggit** [comment]
@a6smile Saya coba di vps / laptop yang fresh tidak ada kendala soal instalasi. coba reset dengan:

1. Klik `Hentikan` (MySQL)
2. Masuk ke console alphp, hapus semua data mysql dengan `rm -rf data`
3. Klik `Mulai` (MySQL)

Mengenai masalah port coba edit bagian ini https://github.com/gnulinuxid/alphp/commit/692ca9d73f147c0dd8f67a08c2125a0aab6b11d5

Sementara silahkan coba edit dan restart MySQL.

**Comment by a6smile** [comment]
Terima kasih, sudah fix. saya pake config yang versi 5.6 dan berjalan dengan baik.

**Comment by nggit** [comment]
#fixed https://github.com/gnulinuxid/alphp/commit/692ca9d73f147c0dd8f67a08c2125a0aab6b11d5
